name: Build search index
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**/index.md'
      - 'scripts/generate-search-index.js'
      - '.github/workflows/build-search-index.yml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Generate index
        env:
          BASEURL: ${{ github.event.repository.name && format('/{0}', github.event.repository.name) }}
        run: |
          node scripts/generate-search-index.js
      - name: Commit index
        uses: EndBug/add-and-commit@v9
        with:
          add: 'assets/search-index.json'
          message: 'chore(search): update search index [skip ci]'
          default_author: github_actions
