name: Internal link & assets check (html-proofer)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install gems
        run: |
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build site
        run: |
          bundle exec jekyll build --trace

      - name: Install html-proofer
        run: |
          gem install html-proofer

      - name: Run html-proofer (internal only)
        run: |
          htmlproofer ./_site \
            --disable-external \
            --check-html \
            --empty-alt-ignore \
            --allow-hash-href \
            --url-ignore "^mailto:"
