name: Link check (Pages site)

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v1.10.1
        with:
          args: >
            --verbose
            --accept 200,206,301,302,429
            --exclude-mail
            --max-concurrency 8
            https://ootakazuhiko.github.io/competitive_programming_book/
          fail: false

