name: Link check (Pages site)

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'assets/**'
      - 'index.md'
      - '_config.yml'
      - '_layouts/**'
      - '_includes/**'

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v2.0.2
        continue-on-error: true
        with:
          args: >
            --verbose
            --accept 200,206,301,302,429
            --exclude-mail
            --max-concurrency 8
            https://ootakazuhiko.github.io/competitive_programming_book/
          fail: false
